blank_issues_enabled: false
contact_links:
  - name: Security Issues
    url: mailto:hello@znci.dev
    about: Please do not report security issues here. Click this link to email us and we'll get your issue sorted out.
  - name: Security Issues
    url: mailto:hello@znci.dev
    about: Please do not report security issues here. Click this link to email us and we'll get your issue sorted out.
   - name: Security Issues
    url: mailto:hello@znci.dev
    about: Please do not report security issues here. Click this link to email us and we'll get your issue sorted out.
